version: '2'
services:
  db:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=<%= ENV['POSTGRES_PASSWORD'] %>
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      PGDATABASE: adopt_a_thing_development
      PGUSER: postgres
      PGHOST: db
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
